name: Spleef
version: 0.1
author: SubSide
main: subside.plugins.spleef.Spleef
description: Spleef
depend: [GameFramework]
commands:
  spleef:
    description: global command
    permission-message: Sorry, you don't have permissions to use this command.